[versions]
java = "21"
springBoot = "4.0.3"
springCloud = "2025.1.1"

mysql = "8.4.0"
querydsl = "5.1.0"
lombok = "1.18.36"

[libraries]
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-starter-data-redis = { group = "org.springframework.boot", name = "spring-boot-starter-data-redis" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }

spring-kafka = { group = "org.springframework.kafka", name = "spring-kafka" }

mysql-connector-j = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysql" }
querydsl-jpa = { group = "com.querydsl", name = "querydsl-jpa", version.ref = "querydsl" }
querydsl-apt = { group = "com.querydsl", name = "querydsl-apt", version.ref = "querydsl" }

lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

spring-cloud-dependencies = { group = "org.springframework.cloud", name = "spring-cloud-dependencies", version.ref = "springCloud" }

[bundles]
persistence = ["spring-boot-starter-data-jpa", "mysql-connector-j"]
querydsl = ["querydsl-jpa", "querydsl-apt"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
